### ISSUE TITLE
Communication to attendees

### ISSUE THREAD

**Issue by mmesiti** [MarieHouillon/2023-10-19-kit#4]
I think we need to send an email to all registered participants with contents like
1. Address of the notesharing pad (https://pad.gwdg.de/yGjdI0AoRQmzHGf4L_hiVg?view)
2. Reminder of the logistics (where the course is)
3. Reminder of the setup steps to download and install Git and Anaconda
4. Anything else?

I am sure you've already done something similar before, just wanted to add my thoughts about this.

**Comment by MarieHouillon** [comment]
Hi,

This is the email I usually send (adapted with your comments):


Hello,

We are excited about the Software Carpentry workshop coming on October 19th and 20th at KIT and hope you are too!

A few notes: 

- This workshop will take place in person, in Pool H, Building 20.21, Zirkel 2, 76131 Karlsruhe.

- Please notify us as soon as possible if you are finally not able to take part to the workshop, so that we can offer your seat to someone else.

- Be sure to complete the Pre-workshop Survey: https://carpentries.typeform.com/to/wi32rS?slug=2023-10-19-kit. We use this to calibrate the pace of the workshop and, together with a post-workshop survey, to assess how it went.

- Make sure you have the necessary software installed on the laptop you will bring to the workshop: the Bash shell, Git and Python. The instructions for installing them are available on the workshop's website: https://mariehouillon.github.io/2023-10-19-kit/. If you have any trouble, send us an email or come a little early on the 29th morning. Someone will be there by 8:00 to help with installation issues.

- We are committed to ensuring a welcoming and respectful environment during our workshops, that is why each participant is asked to abide by The Carpentries Code of Conduct (http://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).

- During the workshop, we will use a collaborative notepad, accessible at https://pad.gwdg.de/yGjdI0AoRQmzHGf4L_hiVg?view (no action needed there before the workshop). 

Coffee and little snacks will be provided during coffee breaks. The lunch breaks will take place from 12:30 to 13:30 but lunch will not be provided. For people willing to eat at Mensa am Adenauerring, we have booked a table there so that we can eat together.

We are committed to making sure that the workshop is accessible to everyone. Please tell us if there is anything we should know in advance in order to make the workshop accessible for you (e.g. sign-language interpreters, large-print handouts, lactation facilities).

More information about the workshop is available on the website: https://mariehouillon.github.io/2023-10-19-kit/. Let us know if you have any questions, otherwise we will see you on October 19th morning.

Looking forward to seeing you soon!

Best,

Your instructors,
Michele, Tomas and Marie

**Comment by MarieHouillon** [comment]
I can send this email whenever I get confirmation from your side.

**Comment by mmesiti** [comment]
It looks perfect, I would dare to suggest only the following changes (which you are free to ignore):
- possibly emphasize the most important parts in bold (the bits about the cancellation, the setup, and maybe the pre-workshop survey)
- "We are attached to ensure" - I never heard this way of saying. Does it mean something like "We are committed to ensure" or "We strive to ensure"? But hey, I'm not an Oxford dictionary.

For the rest it's surely better than anything I could write myself.

**Comment by MarieHouillon** [comment]
Hi, here is the corrected text. Yes indeed, this doesn't seem to be a thing, it was a direct translation from a French expression.


Hello,

We are excited about the Software Carpentry workshop coming on October 19th and 20th at KIT and hope you are too!

A few notes: 

- This workshop will take place in person, in Pool H, Building 20.21, Zirkel 2, 76131 Karlsruhe.

- **Please notify us as soon as possible if you are finally not able to take part to the workshop**, so that we can offer your seat to someone else.

- **Be sure to complete the Pre-workshop Survey**: https://carpentries.typeform.com/to/wi32rS?slug=2023-10-19-kit. We use this to calibrate the pace of the workshop and, together with a post-workshop survey, to assess how it went.

- **Make sure you have the necessary software installed on the laptop you will bring** to the workshop: the Bash shell, Git and Python. The instructions for installing them are available on the workshop's website: https://mariehouillon.github.io/2023-10-19-kit/. If you have any trouble, send us an email or come a little early on the 29th morning. Someone will be there by 8:00 to help with installation issues.

- We are committed to ensuring a welcoming and respectful environment during our workshops, that is why each participant is asked to abide by The Carpentries Code of Conduct (http://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).

- During the workshop, we will use a collaborative notepad, accessible at https://pad.gwdg.de/yGjdI0AoRQmzHGf4L_hiVg?view (no action needed there before the workshop). 

Coffee and little snacks will be provided during coffee breaks. The lunch breaks will take place from 12:30 to 13:30 but lunch will not be provided. For people willing to eat at Mensa am Adenauerring, we have booked a table there so that we can eat together.

We are committed to making sure that the workshop is accessible to everyone. Please tell us if there is anything we should know in advance in order to make the workshop accessible for you (e.g. sign-language interpreters, large-print handouts, lactation facilities).

More information about the workshop is available on the website: https://mariehouillon.github.io/2023-10-19-kit/. Let us know if you have any questions, otherwise we will see you on October 19th morning.

Looking forward to seeing you soon!

Best,

Your instructors,
Michele, Tomas and Marie

**Comment by MarieHouillon** [comment]
The email has been sent to the participants.
